---
title: "ORGANOID ANALYSES"
author: "Matthew J Shannon"
date: "11/05/2021"
output: html_document
---

# Load all dependencies

```{r}
devtools::install_github ('chris-mcginnis-ucsf/DoubletFinder')
devtools::install_github ('satijalab/seurat-wrappers')
 remotes::install_github ("mojaveazure/seurat-disk")
install.packages         ('Seurat')
install.packages         ('modes')
install.packages         ('fields')
library                  (Seurat)
library                  (Matrix)
library                  (dplyr)
library                  (ggplot2)
library                  (cowplot)
library                  (tibble)
library                  (readxl)
library                  (sctransform)
library                  (fields)
library                  (KernSmooth)
library                  (ROCR)
library                  (parallel)
library                  (reshape2)
library                  (pheatmap)
library                  (DoubletFinder)
library                  (clustree)
library                  (limma)
library                  (plotly)
library                  (SeuratWrappers)
library                  (SeuratDisk)
library                  (velocyto.R)
library                  (RColorBrewer)
library                  (xlsx)
library                  (enrichplot)
```

# All stem-cell derived organoids

```{r, Figure 3D UMAP}
pdf         ("StemCellOrgs_10X_UMAP.pdf", width = 10, height = 10)
UMAPPlot    (stemorganoids,
             label      = TRUE,
             label.size = 15,
             pt.size    = 5) + 
             theme    (text          = element_text (size = 40))     + 
             theme    (axis.text     = element_text (size = 35))     + 
             theme    (axis.title.x  = element_text (face = "bold")) +
             theme    (axis.title.y  = element_text (face = "bold")) +
             NoLegend ()
dev.off     ()
```

```{r, Supplemental figure 4}
# Re-run UMAPs that you have accurate calculations for all UMAP(s)
 stemorganoids3D <- RunUMAP (stemorganoids, dims = 1:50, n.components = 3L)

# Extract UMAP information from Seurat Object
          umap_1 <- stemorganoids3D [["umap"]]@cell.embeddings [ , 1]
          umap_2 <- stemorganoids3D [["umap"]]@cell.embeddings [ , 2]
          umap_3 <- stemorganoids3D [["umap"]]@cell.embeddings [ , 3]

# Visualize what headings are called so that you can extract them to form a dataframe
Embeddings (object = stemorganoids3D, reduction = "umap")

# Prepare a dataframe for cell plotting
       plot.data <- FetchData (object = stemorganoids3D, vars = c("UMAP_1", "UMAP_2", "UMAP_3", "seurat_clusters"))

# Make a column of row name identities (these will be your cell/barcode names)
 plot.data$label <- paste (plot.data$seurat_clusters)

# Plot your data, in this example my Seurat object had 21 clusters (0-20)
stemorganoids3D2 <- plot_ly (data      =  plot.data, 
                              x         = ~UMAP_1,
                              y         = ~UMAP_2,
                              z         = ~UMAP_3, 
                              color     = ~seurat_clusters, 
                              colors    = c("#ff7f0e",
                                            "#1f77b4",
                                            "#2ca02c",
                                            "#d62728",
                                            "#e377c2",
                                            "#8c564b",
                                            "#9467bd"),
                              type      = "scatter3d", 
                              mode      = "markers", 
                              marker    = list (size = 5, width = 2), # Controls size of points
                              text      = ~label,                     # This is that extra column we made earlier for which we will use for cell ID
                              hoverinfo = "text" )                    # Hovering your mouse pointer over a point shows cell names
stemorganoids3D2
htmlwidgets::saveWidget      (stemorganoids3D2, "3D_ORG_UMAP.html")
rm                           (stemorganoids3D)
rm                           (stemorganoids3D2)
```

```{r}
DefaultAssay (object = stemorganoids) <- "RNA"
```

```{r}
stemorganoids.markers <- FindAllMarkers (object   = stemorganoids,
                                         only.pos = TRUE,
                                         min.pct  = 0.25,
                                         test.use = "MAST")
```

```{r}
stemorganoids.markers %>% group_by (cluster) %>% top_n (10, avg_log2FC)
```

```{r, Table 2}
write.xlsx (stemorganoids.markers, file = "Stemorganoids.markers.xlsx")
```

```{r, Figure 3D heatmap}
DefaultAssay  (object = STEMorg) <- "RNA"

cluster.averages <- AverageExpression (STEMorg, return.seurat = TRUE)

genelist         <- c("ERVFRD-1", "ERVV-1", "SDC1",  "TFAP2C", "TFAP2A",
                      "GATA3",    "EGFR",   "GATA2", "KRT7",   "HLA-G",
                      "ITGA5",    "NOTCH2", "ITGA1", "BMP4",   "NOTCH1",
                      "SOX9",     "ITGA2",  "YAP1",  "TEAD4",  "TP63",
                      "ITGA6",    "BCAM",   "PAGE4", "ELF5",   "MKI67", "CCNA2")

my_levels        <- c("CTB 1", "CTB 2", "CTB 3", "cCTB", "EVT 1", "EVT 2", "SCTp")

cluster.averages@active.ident <- factor (cluster.averages@active.ident, levels = my_levels)

pdf                  ("StemCellOrgs_gene_markers_heat.pdf", width = 15, height = 20)
DoHeatmap            (cluster.averages,
                      features     = genelist,
                      size         = 5,
                      angle        = 270,
                      hjust        = 1,
                      group.bar    = FALSE,
                      draw.lines   = FALSE,
                      raster       = FALSE) +
scale_fill_gradientn (colours      = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu"))) (100)) +
theme                (text         = element_text     (size  = 40)) + 
theme                (axis.text    = element_text     (size  = 35)) + 
theme                (axis.title.y = element_text     (face  = "bold")) +
theme                (axis.text.y  = element_text     (face  = "italic", hjust = 1)) +
theme                (axis.text.x  = element_text     (vjust = 0.5, hjust = 0, face = "bold", angle = 270)) + 
theme                (legend.text  = element_text     (size  = 15)) +
NoLegend             ()
dev.off              ()
```

# CT27 specific organoids

```{r, Figure 3E CT27 UMAP}
pdf         ("CT27_10X_UMAP.pdf", width = 10, height = 10)
UMAPPlot    (CT27,
             label      = TRUE,
             label.size = 15,
             pt.size    = 5) + 
             theme    (text          = element_text (size = 40))     + 
             theme    (axis.text     = element_text (size = 35))     + 
             theme    (axis.title.x  = element_text (face = "bold")) +
             theme    (axis.title.y  = element_text (face = "bold")) +
             NoLegend ()
dev.off     ()
```

```{r}
DefaultAssay (object = CT27) <- "RNA"
```

```{r}
CT27.markers <- FindAllMarkers (object   = CT27,
                                only.pos = TRUE,
                                min.pct  = 0.25,
                                test.use = "MAST")
```

```{r}
CT27.markers %>% group_by (cluster) %>% top_n (10, avg_log2FC)
```

```{r}
write.xlsx (CT27.markers, file = "Stemorganoids.markers.xlsx")
```

```{r, Figure 3E CT27 heatmap}
DefaultAssay  (object = CT27) <- "RNA"

cluster.averages <- AverageExpression (CT27, return.seurat = TRUE)

genelist         <- c("ERVFRD-1", "ERVV-1", "SDC1",  "TFAP2C", "TFAP2A",
                      "GATA3",    "EGFR",   "GATA2", "KRT7",   "HLA-G",
                      "ITGA5",    "NOTCH2", "ITGA1", "BMP4",   "NOTCH1",
                      "SOX9",     "ITGA2",  "YAP1",  "TEAD4",  "TP63",
                      "ITGA6",    "BCAM",   "PAGE4", "ELF5",   "MKI67", "CCNA2")

my_levels        <- c("CTB 1", "CTB 2", "cCTB", "EVT 1", "SCTp")

cluster.averages@active.ident <- factor (cluster.averages@active.ident, levels = my_levels)

pdf                  ("CT27_gene_markers_heat.pdf", width = 15, height = 20)
DoHeatmap            (cluster.averages,
                      features     = genelist,
                      size         = 5,
                      angle        = 270,
                      hjust        = 1,
                      group.bar    = FALSE,
                      draw.lines   = FALSE,
                      raster       = FALSE) +
scale_fill_gradientn (colours      = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu"))) (100)) +
theme                (text         = element_text     (size  = 40)) + 
theme                (axis.text    = element_text     (size  = 35)) + 
theme                (axis.title.y = element_text     (face  = "bold")) +
theme                (axis.text.y  = element_text     (face  = "italic", hjust = 1)) +
theme                (axis.text.x  = element_text     (vjust = 0.5, hjust = 0, face = "bold", angle = 270)) + 
theme                (legend.text  = element_text     (size  = 15)) +
NoLegend             ()
dev.off              ()
```

```{r, Figure 3J CT27 UMAP}
pdf          ("CT27_BCAM.pdf", width = 10, height = 10)
FeaturePlot  (CT27,
              features   = c("BCAM"),
              label      = FALSE,
              pt.size    = 5,
              min.cutoff = 0,
              order      = TRUE,
              cols       = c("grey", "red")) + 
              theme    (text          = element_text (size = 40))     + 
              theme    (axis.text     = element_text (size = 35))     + 
              theme    (axis.title.x  = element_text (face = "bold")) +
              theme    (axis.title.y  = element_text (face = "bold")) +
              NoLegend ()
dev.off      ()
```

# CT29 specific organoids

```{r, Figure 3E CT29 UMAP}
pdf         ("CT29_10X_UMAP.pdf", width = 10, height = 10)
UMAPPlot    (CT29,
             label      = TRUE,
             label.size = 15,
             pt.size    = 5) + 
             theme    (text          = element_text (size = 40))     + 
             theme    (axis.text     = element_text (size = 35))     + 
             theme    (axis.title.x  = element_text (face = "bold")) +
             theme    (axis.title.y  = element_text (face = "bold")) +
             NoLegend ()
dev.off     ()
```

```{r}
DefaultAssay (object = CT29) <- "RNA"
```

```{r}
CT29.markers <- FindAllMarkers (object   = CT29,
                                only.pos = TRUE,
                                min.pct  = 0.25,
                                test.use = "MAST")
```

```{r}
CT29.markers %>% group_by (cluster) %>% top_n (10, avg_log2FC)
```

```{r}
write.xlsx (CT29.markers, file = "Stemorganoids.markers.xlsx")
```

```{r, Figure 3E CT29 heatmap}
DefaultAssay  (object = CT29) <- "RNA"

cluster.averages <- AverageExpression (CT29, return.seurat = TRUE)

genelist         <- c("ERVFRD-1", "ERVV-1", "SDC1",  "TFAP2C", "TFAP2A",
                      "GATA3",    "EGFR",   "GATA2", "KRT7",   "HLA-G",
                      "ITGA5",    "NOTCH2", "ITGA1", "BMP4",   "NOTCH1",
                      "SOX9",     "ITGA2",  "YAP1",  "TEAD4",  "TP63",
                      "ITGA6",    "BCAM",   "PAGE4", "ELF5",   "MKI67", "CCNA2")

my_levels        <- c("CTB 1", "CTB 2", "cCTB", "EVT 1", "SCTp")

cluster.averages@active.ident <- factor (cluster.averages@active.ident, levels = my_levels)

pdf                  ("CT27_gene_markers_heat.pdf", width = 15, height = 20)
DoHeatmap            (cluster.averages,
                      features     = genelist,
                      size         = 5,
                      angle        = 270,
                      hjust        = 1,
                      group.bar    = FALSE,
                      draw.lines   = FALSE,
                      raster       = FALSE) +
scale_fill_gradientn (colours      = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu"))) (100)) +
theme                (text         = element_text     (size  = 40)) + 
theme                (axis.text    = element_text     (size  = 35)) + 
theme                (axis.title.y = element_text     (face  = "bold")) +
theme                (axis.text.y  = element_text     (face  = "italic", hjust = 1)) +
theme                (axis.text.x  = element_text     (vjust = 0.5, hjust = 0, face = "bold", angle = 270)) + 
theme                (legend.text  = element_text     (size  = 15)) +
NoLegend             ()
dev.off              ()
```

```{r, Figure 3J CT29 UMAP}
pdf          ("CT29_BCAM.pdf", width = 10, height = 10)
FeaturePlot  (CT29,
              features   = c("BCAM"),
              label      = FALSE,
              pt.size    = 5,
              min.cutoff = 0,
              order      = TRUE,
              cols       = c("grey", "red")) + 
              theme    (text          = element_text (size = 40))     + 
              theme    (axis.text     = element_text (size = 35))     + 
              theme    (axis.title.x  = element_text (face = "bold")) +
              theme    (axis.title.y  = element_text (face = "bold")) +
              NoLegend ()
dev.off      ()
```

# CT30 specific organoids

```{r, Figure 3E CT30 UMAP}
pdf         ("CT30_10X_UMAP.pdf", width = 10, height = 10)
UMAPPlot    (CT30,
             label      = TRUE,
             label.size = 15,
             pt.size    = 5) + 
             theme    (text          = element_text (size = 40))     + 
             theme    (axis.text     = element_text (size = 35))     + 
             theme    (axis.title.x  = element_text (face = "bold")) +
             theme    (axis.title.y  = element_text (face = "bold")) +
             NoLegend ()
dev.off     ()
```

```{r}
DefaultAssay (object = CT30) <- "RNA"
```

```{r}
CT30.markers <- FindAllMarkers (object   = CT30,
                                only.pos = TRUE,
                                min.pct  = 0.25,
                                test.use = "MAST")
```

```{r}
CT30.markers %>% group_by (cluster) %>% top_n (10, avg_log2FC)
```

```{r}
write.xlsx (CT30.markers, file = "Stemorganoids.markers.xlsx")
```

```{r, Figure 3E CT30 heatmap}
DefaultAssay  (object = CT30) <- "RNA"

cluster.averages <- AverageExpression (CT30, return.seurat = TRUE)

genelist         <- c("ERVFRD-1", "ERVV-1", "SDC1",  "TFAP2C", "TFAP2A",
                      "GATA3",    "EGFR",   "GATA2", "KRT7",   "HLA-G",
                      "ITGA5",    "NOTCH2", "ITGA1", "BMP4",   "NOTCH1",
                      "SOX9",     "ITGA2",  "YAP1",  "TEAD4",  "TP63",
                      "ITGA6",    "BCAM",   "PAGE4", "ELF5",   "MKI67", "CCNA2")

my_levels        <- c("CTB 1", "CTB 2", "cCTB", "EVT 1", "SCTp")

cluster.averages@active.ident <- factor (cluster.averages@active.ident, levels = my_levels)

pdf                  ("CT27_gene_markers_heat.pdf", width = 15, height = 20)
DoHeatmap            (cluster.averages,
                      features     = genelist,
                      size         = 5,
                      angle        = 270,
                      hjust        = 1,
                      group.bar    = FALSE,
                      draw.lines   = FALSE,
                      raster       = FALSE) +
scale_fill_gradientn (colours      = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu"))) (100)) +
theme                (text         = element_text     (size  = 40)) + 
theme                (axis.text    = element_text     (size  = 35)) + 
theme                (axis.title.y = element_text     (face  = "bold")) +
theme                (axis.text.y  = element_text     (face  = "italic", hjust = 1)) +
theme                (axis.text.x  = element_text     (vjust = 0.5, hjust = 0, face = "bold", angle = 270)) + 
theme                (legend.text  = element_text     (size  = 15)) +
NoLegend             ()
dev.off              ()
```

```{r, Figure 3J CT30 UMAP}
pdf          ("CT30_BCAM.pdf", width = 10, height = 10)
FeaturePlot  (CT30,
              features   = c("BCAM"),
              label      = FALSE,
              pt.size    = 5,
              min.cutoff = 0,
              order      = TRUE,
              cols       = c("grey", "red")) + 
              theme    (text          = element_text (size = 40))     + 
              theme    (axis.text     = element_text (size = 35))     + 
              theme    (axis.title.x  = element_text (face = "bold")) +
              theme    (axis.title.y  = element_text (face = "bold")) +
              NoLegend ()
dev.off      ()
```

# Placental villi versus Trophoblast Organoid CTB Origin Comparison

```{r}
# Set RNA assay for DEG
DefaultAssay (object = Trophoblasts)  <- "RNA"
DefaultAssay (object = stemorganoids) <- "RNA"

villusCTBoriginmarkers   <- FindMarkers (object = Trophoblasts,
                            ident.1             = "CTB 2",
                            ident.2             = NULL,
                            assay               = "RNA",
                            test.use            = "MAST",
                            logfc.threshold     = -Inf,
                            min.pct             = -Inf,
                            min.diff.pct        = -Inf,
                            only.pos            = TRUE,
                            slot                = "data")
villusCTBoriginmarkers   %>% top_n (50, avg_log2FC)

organoidCTBoriginmarkers <- FindMarkers (object = stemorganoids,
                            ident.1             = "CTB 1",
                            ident.2             = NULL,
                            assay               = "RNA",
                            test.use            = "MAST",
                            logfc.threshold     = -Inf,
                            min.pct             = -Inf,
                            min.diff.pct        = -Inf,
                            only.pos            = TRUE,
                            slot                = "data")
organoidCTBorigin_markers %>% top_n (50, avg_log2FC)

CTBorigin_markers <- rbind (villusCTBorigin_markers, organoidCTBorigin_markers)
```

```{r, Figure 3F}
venn.diagram (x              = list (row.names (villusCTBorigin_markers),
                                     row.names (organoidCTBorigin_markers)),
              category.names = c    ("Tissue", "Organoid"),
              filename       = 'Full_CTBorigin_comparison_Venn.png',
              output         = TRUE,
              imagetype      = "png",
              scaled         = FALSE,
              col            = "black",
              cat.cex        = 2,
              margin         = 0.15)
```

```{r}
venn_table <- get.venn.partitions (x             = list (row.names (  villusCTBorigin_markers),
                                                         row.names (organoidCTBorigin_markers)),
                                   force.unique  = TRUE,
                                   keep.elements = TRUE,
                                   hierarchical  = FALSE)
venn_table
venn_table$..values..
 
RVenn1 <- venn_table$..values..$`1`
RVenn2 <- venn_table$..values..$`2`
RVenn3 <- venn_table$..values..$`3`
```

```{r, Table 3}
write.xlsx (RVenn1, file = "Fig3_origin_venn1.xlsx")
write.xlsx (RVenn2, file = "Fig3_origin_venn2.xlsx")
write.xlsx (RVenn3, file = "Fig3_origin_venn3.xlsx")
```

# Placental villi versus Trophoblast Organoid CTB Origin Differential Gene Expression Analysis

```{r}
villiorigin    <- subset (Trophoblasts,  idents =  c("CTB 2"))
organoidorigin <- subset (stemorganoids, idents =  c("CTB 1"))

Origin <- merge (villiorigin,
                 y = organoidorigin,
                 merge.data = TRUE,
                 project = "Origin")
Origin
```

```{r}
# Origin Differential Expression
DefaultAssay                 (object = Origin) <- "RNA"

Origin.MAST   <- FindMarkers (Origin,
                              ident.1         = 'CTB 2',
                              ident.2         = 'CTB 1',
                              test.use        = "MAST",
                              logfc.threshold = -Inf,
                              min.pct         = -Inf,
                              min.diff.pct    = -Inf)
```

```{r, Table 4}
write.xlsx (Origin.MAST,  file = "Origin_DEG.markers.xlsx")
```

```{r, Figure 3G}
pdf                        ("Origin_DEG.pdf", width = 12.5, height = 10)
EnhancedVolcano            (Origin.MAST,
                            lab             = rownames (Origin.MAST),
                            x               = "avg_log2FC",
                            y               = "p_val_adj",
                            FCcutoff        = 1.00,
                            pCutoff         = 10e-125,
                            pointSize       = 4.0,
                            col             = c('grey', 'grey', 'grey', 'red'),
                            colAlpha        = 1,
                            gridlines.major = FALSE,
                            gridlines.minor = FALSE) + NoLegend () + ggtitle (NULL)
dev.off                    ()
```

```{r}
# Gene Ontology on DEG Results 
                            Origin_list  <- Origin.MAST$avg_log2FC
# name the vector
              names        (Origin_list) <- rownames (Origin.MAST)
# sort the list in decreasing order (required for clusterProfiler)
Origin_list = sort         (Origin_list, decreasing = TRUE)

gseOrigin <-  gseGO        (geneList      = Origin_list, 
                            ont           = "ALL", 
                            keyType       = "SYMBOL", 
                            nPerm         = 100000, 
                            minGSSize     = 1, 
                            maxGSSize     = 800, 
                            pvalueCutoff  = 0.5, 
                            verbose       = TRUE, 
                            OrgDb         = org.Hs.eg.db, 
                            pAdjustMethod = "BH")
```

```{r, Figure 3H}
pdf     ("Origin_GO.pdf", width = 25, height = 10)
dotplot (gseOrigin, showCategory = 4, split = ".sign") + facet_grid (.~.sign)
dev.off ()
```

# BCAM hi versus BCAM lo Differential Expression Analysis

```{r}
CTB1 <- subset (CT29, idents = "CTB 1")
```

```{r}
Idents (CTB1, WhichCells (CTB1, expression = BCAM >= 0.5, slot = 'data')) <- 'BCAMhi'
Idents (CTB1, WhichCells (CTB1, expression = BCAM == 0.0, slot = 'data')) <- 'BCAMlo'

BCAM.MAST <- FindMarkers (CTB1,
                          ident.1         = 'BCAMhi',
                          ident.2         = 'BCAMlo',
                          test.use        = "MAST",
                          logfc.threshold = -Inf,
                          min.pct         = -Inf,
                          min.diff.pct    = -Inf)
```

```{r, Figure 4G}
Idents       (CT29, WhichCells (CT29, expression = BCAM >= 0.5, slot = 'data')) <- 'BCAMhi'
Idents       (CT29, WhichCells (CT29, expression = BCAM == 0.0, slot = 'data')) <- 'BCAMlo'

DefaultAssay (object = CT29) <- "RNA"

cluster.averages <- AverageExpression (CT29, return.seurat = TRUE)

genelist         <- c("BCAM", "LRAP1", "PEG10",  "SPINT2", "EPCAM", "LAMB1", "PDLIM1", "HMGB3")

my_levels        <- c("BCAMhi", "BCAMlo")

cluster.averages@active.ident <- factor (cluster.averages@active.ident, levels = my_levels)

pdf                  ("CT29_BCAM_DEG.pdf", width = 15, height = 20)
DoHeatmap            (cluster.averages,
                      features     = genelist,
                      size         = 5,
                      angle        = 270,
                      hjust        = 1,
                      group.bar    = FALSE,
                      draw.lines   = FALSE,
                      raster       = FALSE) +
scale_fill_gradientn (colours      = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu"))) (100)) +
theme                (text         = element_text     (size  = 40)) + 
theme                (axis.text    = element_text     (size  = 35)) + 
theme                (axis.title.y = element_text     (face  = "bold")) +
theme                (axis.text.y  = element_text     (face  = "italic", hjust = 1)) +
theme                (axis.text.x  = element_text     (vjust = 0.5, hjust = 0, face = "bold", angle = 270)) + 
theme                (legend.text  = element_text     (size  = 15)) +
NoLegend             ()
dev.off              ()
```

