---
title: "PSEUDOTIME ANALYSES"
author: "Matthew J Shannon"
date: "11/05/2021"
output: html_document
---

# Load all dependencies

```{r, include = FALSE}
devtools::install_github  ('chris-mcginnis-ucsf/DoubletFinder')
if     (!requireNamespace ("BiocManager", quietly = TRUE) )
install.packages          ("BiocManager")
install.packages          ('Seurat')
install.packages          ('modes')
install.packages          ('fields')
BiocManager::install      ("monocle")
library                   (Seurat)
library                   (Matrix)
library                   (dplyr)
library                   (ggplot2)
library                   (cowplot)
library                   (tibble)
library                   (readxl)
library                   (sctransform)
library                   (fields)
library                   (KernSmooth)
library                   (ROCR)
library                   (parallel)
library                   (reshape2)
library                   (pheatmap)
library                   (DoubletFinder)
library                   (monocle)
library                   (limma)
```

# Read in and convert the trophoblast dataset

```{r}
DimPlot (object = Trophoblasts, reduction = "umap", label = TRUE) + NoLegend ()
```

```{r}
VlnPlot (object = Trophoblasts, features = c("BCAM"),     assay = "RNA") + NoLegend ()
VlnPlot (object = Trophoblasts, features = c("EGFR"),     assay = "RNA") + NoLegend ()
VlnPlot (object = Trophoblasts, features = c("TP63"),     assay = "RNA") + NoLegend ()
VlnPlot (object = Trophoblasts, features = c("SPINT1"),   assay = "RNA") + NoLegend ()
VlnPlot (object = Trophoblasts, features = c("PAGE4"),    assay = "RNA") + NoLegend ()
VlnPlot (object = Trophoblasts, features = c("TINAGL1"),  assay = "RNA") + NoLegend ()
```

```{r}
Trophoblast.monocle <- as.CellDataSet (Trophoblasts, assay  =   "RNA")
                       rm             (Trophoblasts)
```

# Monocle2 Analysis

```{r}
Trophoblast.monocle <- estimateSizeFactors (Trophoblast.monocle)
Trophoblast.monocle <- estimateDispersions (Trophoblast.monocle)
```

```{r}
Trophoblast.monocle <- detectGenes (Trophoblast.monocle, min_expr = 0.1)
                       print       (head (fData (Trophoblast.monocle)))
```

```{r}
Trophoblast.monocle_expressed_genes <- row.names (subset (fData (Trophoblast.monocle), num_cells_expressed >= 10))
```

```{r}
 ERVFRD_id             <- row.names            (subset (fData (Trophoblast.monocle), gene_short_name == "ERVFRD-1"))
 HLAG_id               <- row.names            (subset (fData (Trophoblast.monocle), gene_short_name == "HLA-G"   ))
 EGFR_id               <- row.names            (subset (fData (Trophoblast.monocle), gene_short_name == "EGFR"    ))
 SPINT1_id             <- row.names            (subset (fData (Trophoblast.monocle), gene_short_name == "SPINT1"  ))

Trophoblast.monocle.2  <- newCellTypeHierarchy ()

Trophoblast.monocle.2  <- addCellType          (Trophoblast.monocle.2,
                                                "SCT",
                                               classify_func = function (x) { x [ERVFRD_id,  ]  >= 2   })

Trophoblast.monocle.2  <- addCellType          (Trophoblast.monocle.2,
                                                "EVT",
                                               classify_func = function (x) { x [HLAG_id,    ]  >= 3   })

Trophoblast.monocle.2  <- addCellType          (Trophoblast.monocle.2,
                                                "CTB",
                                               classify_func = function (x) { x [EGFR_id,    ]  >  3.0 &
                                                                              x [SPINT1_id,  ]  >  3.0 &
                                                                              x [ERVFRD_id,  ]  <  2 &
                                                                              x [HLAG_id,    ]  <  3 })

Trophoblast.monocle    <- classifyCells        (Trophoblast.monocle, Trophoblast.monocle.2)
```

```{r}
marker_diff            <- markerDiffTable (Trophoblast.monocle   [Trophoblast.monocle_expressed_genes, ],
                                           Trophoblast.monocle.2,
                                           cores = 1)
```

```{r}
semisup_clustering_genes <- row.names (marker_diff)[order (marker_diff$qval)][1:1500]
```
 
```{r}
Trophoblast.monocle <- setOrderingFilter (Trophoblast.monocle, semisup_clustering_genes)
```

```{r}
Trophoblast.monocle <- reduceDimension   (Trophoblast.monocle,
                                          max_components = 2,
                                          method         = 'DDRTree',
                                          norm_method    = 'none',
                                          pseudo_expr    = 0)
Trophoblast.monocle <- orderCells        (Trophoblast.monocle)
Trophoblast.monocle <- orderCells        (Trophoblast.monocle, root_state = 3)
```

```{r}
plot_cell_trajectory (Trophoblast.monocle, color_by = "seurat_clusters") + theme      (legend.position = "right")
plot_cell_trajectory (Trophoblast.monocle, color_by = "Pseudotime")      + theme      (legend.position = "right")
plot_cell_trajectory (Trophoblast.monocle, color_by = "GA")              + theme      (legend.position = "right")
plot_cell_trajectory (Trophoblast.monocle)                               + facet_grid (~State)
plot_cell_trajectory (Trophoblast.monocle, color_by = "seurat_clusters") + facet_grid (~seurat_clusters)
plot_cell_trajectory (Trophoblast.monocle, color_by = "seurat_clusters") + facet_grid (~GA)
plot_cell_trajectory (Trophoblast.monocle, color_by = "seurat_clusters") + facet_grid (~Sex)
```

```{r}
plot_cell_trajectory (Trophoblast.monocle, markers = "HLA-G",    use_color_gradient = TRUE) + NoLegend ()
plot_cell_trajectory (Trophoblast.monocle, markers = "ERVFRD-1", use_color_gradient = TRUE) + NoLegend ()
plot_cell_trajectory (Trophoblast.monocle, markers = "BCAM",     use_color_gradient = TRUE) + NoLegend ()
plot_cell_trajectory (Trophoblast.monocle, markers = "EGFR",     use_color_gradient = TRUE) + NoLegend ()
plot_cell_trajectory (Trophoblast.monocle, markers = "TP63",     use_color_gradient = TRUE) + NoLegend ()
plot_cell_trajectory (Trophoblast.monocle, markers = "SPINT1",   use_color_gradient = TRUE) + NoLegend ()
plot_cell_trajectory (Trophoblast.monocle, markers = "PAGE4",    use_color_gradient = TRUE) + NoLegend ()
plot_cell_trajectory (Trophoblast.monocle, markers = "TINAGL1",  use_color_gradient = TRUE) + NoLegend ()
```

```{r}
Trophoblast_expressed_genes <- row.names            (subset (fData (Trophoblast.monocle), num_cells_expressed >= 10))
Trophoblast_filtered        <- Trophoblast.monocle  [Trophoblast_expressed_genes, ]
my_genes                    <- row.names            (subset (fData (Trophoblast_filtered), gene_short_name %in% "BCAM"))
Trophoblast_subset          <- Trophoblast_filtered [my_genes, ]

plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters")
plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters") + facet_grid (~GA)
```

```{r}
Trophoblast_expressed_genes <- row.names            (subset (fData (Trophoblast.monocle), num_cells_expressed >= 10))
Trophoblast_filtered        <- Trophoblast.monocle  [Trophoblast_expressed_genes, ]
my_genes                    <- row.names            (subset (fData (Trophoblast_filtered), gene_short_name %in% "EGFR"))
Trophoblast_subset          <- Trophoblast_filtered [my_genes, ]

plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters")
plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters") + facet_grid (~GA)
```

```{r}
Trophoblast_expressed_genes <- row.names            (subset (fData (Trophoblast.monocle), num_cells_expressed >= 10))
Trophoblast_filtered        <- Trophoblast.monocle  [Trophoblast_expressed_genes, ]
my_genes                    <- row.names            (subset (fData (Trophoblast_filtered), gene_short_name %in% "TP63"))
Trophoblast_subset          <- Trophoblast_filtered [my_genes, ]

plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters")
plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters") + facet_grid (~GA)
```

```{r}
Trophoblast_expressed_genes <- row.names            (subset (fData (Trophoblast.monocle), num_cells_expressed >= 10))
Trophoblast_filtered        <- Trophoblast.monocle  [Trophoblast_expressed_genes, ]
my_genes                    <- row.names            (subset (fData (Trophoblast_filtered), gene_short_name %in% "SPINT1"))
Trophoblast_subset          <- Trophoblast_filtered [my_genes, ]

plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters")
plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters") + facet_grid (~GA)
```

```{r}
Trophoblast_expressed_genes <- row.names            (subset (fData (Trophoblast.monocle), num_cells_expressed >= 10))
Trophoblast_filtered        <- Trophoblast.monocle  [Trophoblast_expressed_genes, ]
my_genes                    <- row.names            (subset (fData (Trophoblast_filtered), gene_short_name %in% "PAGE4"))
Trophoblast_subset          <- Trophoblast_filtered [my_genes, ]

plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters")
plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters") + facet_grid (~GA)
```

```{r}
Trophoblast_expressed_genes <- row.names            (subset (fData (Trophoblast.monocle), num_cells_expressed >= 10))
Trophoblast_filtered        <- Trophoblast.monocle  [Trophoblast_expressed_genes, ]
my_genes                    <- row.names            (subset (fData (Trophoblast_filtered), gene_short_name %in% "TINAGL1"))
Trophoblast_subset          <- Trophoblast_filtered [my_genes, ]

plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters")
plot_genes_in_pseudotime       (Trophoblast_subset, color_by = "seurat_clusters") + facet_grid (~GA)
```

```{r}
BEAM_res <- BEAM     (Trophoblast.monocle,
                      branch_point = 1,
                      cores        = 1)

BEAM_res <- BEAM_res [order (BEAM_res$qval), ]
BEAM_res <- BEAM_res [ , c("gene_short_name", "pval", "qval")]
```

```{r}
head (BEAM_res)
```

```{r}
F2D_genes <- row.names (subset (fData (Trophoblast.monocle), gene_short_name %in% c("CDX2",
                                                                                    "TEAD4",
                                                                                    "EPCAM",
                                                                                    "ELF5",
                                                                                    "TP63",
                                                                                    "YAP1",
                                                                                    "ERVFRD-1",
                                                                                    "HLA-G",
                                                                                    "SMAGP",
                                                                                    "SPINT1",
                                                                                    "TINAGL1",
                                                                                    "EFEMP1",
                                                                                    "OLR1",
                                                                                    "ISYNA1",
                                                                                    "DUSP9",
                                                                                    "MORC4",
                                                                                    "SERINC2",
                                                                                    "IFI6",
                                                                                    "GSTA3",
                                                                                    "ACSS1",
                                                                                    "FAM3B",
                                                                                    "SLC22A11",
                                                                                    "MEST",
                                                                                    "PHLDA2",
                                                                                    "MPP1",
                                                                                    "FXYD3",
                                                                                    "PISD",
                                                                                    "PNP",
                                                                                    "SERPINF1",
                                                                                    "BCAM",
                                                                                    "VAMP8",
                                                                                    "COMT")))
```

```{r, Figre 2D}
pdf ("F2D_pseudotime_heatmap.pdf", width = 6, height = 5)
my_branched_heatmap  <- plot_genes_branched_heatmap (Trophoblast.monocle  [F2D_genes, ],
                                                     branch_point        = 1,
                                                     branch_labels       = c("EVT", "SCT"),
                                                     cores               = 1,
                                                     use_gene_short_name = TRUE,
                                                     show_rownames       = TRUE,
                                                     cluster_rows        = FALSE,
                                                     num_clusters        = 1, 
                                                     return_heatmap      = FALSE )
dev.off ()
```

# Monocle3 Analysis

```{r}
if (!requireNamespace    ("BiocManager", quietly = TRUE))
install.packages         ("BiocManager")
BiocManager::install     (version = "3.9")
BiocManager::install     (c('BiocGenerics',
                            'DelayedArray',
                            'DelayedMatrixStats',
                            'limma',
                            'S4Vectors',
                            'SingleCellExperiment',
                            'SummarizedExperiment',
                            'batchelor',
                            'Matrix.utils'))
install.packages          ("devtools")
install.packages          ("rlang", update = TRUE, dependencies = TRUE)
devtools::install_github  ('cole-trapnell-lab/leidenbase', force = TRUE)
Sys.setenv                (R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
devtools::install_github  ('cole-trapnell-lab/monocle3', ref = "develop")
library                   (monocle3)
library                   (Seurat)
remotes::install_version  ("spatstat", version = "1.64-1")
BiocManager::install      ("ggpubr")
library                   (SeuratWrappers)
library                   (ggplot2)
library                   (patchwork)
library                   (magrittr)
library                   (ggpubr)
```

```{r}
cds <- as.cell_data_set      (Trophoblasts, assay = "RNA")
cds <- estimate_size_factors (cds)
cds <- cluster_cells         (cds,
                              reduction_method = c("UMAP"),
                              cluster_method   = "leiden",
                              partition_qval   = 0.05,
                              resolution       = 0.00025)

p1  <- plot_cells            (cds,                               show_trajectory_graph = FALSE)
p2  <- plot_cells            (cds, color_cells_by = "partition", show_trajectory_graph = FALSE)

wrap_plots (p1, p2)
```

```{r}
cds <- learn_graph (cds,
                    use_partition = FALSE,
                    close_loop    = TRUE)
```

```{r, Supplemental figure 3B}
pdf        ("Trophoblasts_monocle3_clusters.pdf", width = 10, height = 10)
plot_cells (cds,
            label_cell_groups             = F,
            label_leaves                  = F,
            label_branch_points           = F,
            color_cells_by                = "seurat_clusters",
            cell_size                     = 2,
            trajectory_graph_color        = "black",
            trajectory_graph_segment_size = 1.25) + NoLegend ()
dev.off    ()
```

```{r}
cds <- order_cells (cds)
```

```{r, Supplemental figure 3A}
pdf        ("Trophoblasts_monocle3_pseudotime.pdf", width = 10, height = 10)
plot_cells (cds,
            color_cells_by                = "pseudotime",
            label_cell_groups             = FALSE,
            label_leaves                  = FALSE,
            label_branch_points           = FALSE,
            graph_label_size              = 1.5,
            cell_size                     = 2,
            trajectory_graph_color        = "black",
            trajectory_graph_segment_size = 1.25) + NoLegend ()
dev.off    ()
```

```{r}
cds_sub <- choose_graph_segments (cds, clear_cds = FALSE)
```

```{r, Supplemental figure 3C}
plot_cells (cds_sub,
            color_cells_by                = "seurat_clusters",
            label_cell_groups             = FALSE,
            label_leaves                  = FALSE,
            label_branch_points           = FALSE,
            graph_label_size              = 1.5,
            cell_size                     = 2,
            trajectory_graph_color        = "black",
            trajectory_graph_segment_size = 1.25) + NoLegend ()
```


